apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: gcr.io/migel/chatws
deploy:
  helm:
    releases:
    - name: chatws
      chartPath: helm/chatws
      valuesFiles:
      - helm/chatws/values.yaml
      skipBuildDependencies: true
      artifactOverrides:
        image: gcr.io/migel/chatws
      imageStrategy:
        helm:
          explicitRegistry: true
