image:
  registry: docker.hub
  repository: migel/chatws
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  ports:
  - port: 8080
    name: grpc

labels:
  tier: backend
  environment: dev

minReadySeconds: 10
strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0

rabbitmq:
  hostname: rabbitmq
  username: admin
  password: bitnami
  port: 5672
