apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatws.name" . }}
  labels:
{{ include "chatws.labels.standard" . | indent 4 }}
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  selector:
    matchLabels:
      app: {{ include "chatws.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "chatws.name" . }}
        release: {{ .Release.Name }}
        {{- range $key, $val := .Values.labels }}
        {{ $key }}: {{ $val }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{.Values.image.registry}}/{{.Values.image.repository}}:{{.Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        {{- range $key, $val := .Values.service.ports }}
        - containerPort: {{ $val.port }}
        {{- end }}
        env:
        - name: RABBITMQ_HOST
          value: {{ .Values.rabbitmq.hostname | quote }}
        - name: RABBITMQ_PORT
          value: {{ .Values.rabbitmq.port | quote }}
        - name: RABBITMQ_USER
          value: {{ .Values.rabbitmq.username | quote }}
        - name: RABBITMQ_PASSWORD
          value: {{ .Values.rabbitmq.password | quote }}
