apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatws.name" .}}
  labels:
{{ include "chatws.labels.standard" . | indent 4 }}
    {{- range $key, $val := .Values.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $val := .Values.service.ports }}
    -
      {{- range $pkey, $pval := $val }}
      {{ $pkey}}: {{ $pval }}
      {{- end }}
    {{- end }}
  selector:
    app: {{ include "chatws.name" . }}
    release: {{ .Release.Name }}
